# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7.3
language: objective-c
rvm: 2.2.3
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- xcodebuild -workspace Example/MRLCircleChart.xcworkspace -scheme MRLCircleChart-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO
