osx_image: xcode7.3
language: objective-c
rvm: 2.2.3
before_install:
- gem install cocoapods
- gem install xcpretty
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -workspace Example/MRLCircleChart.xcworkspace -scheme MRLCircleChart-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
notifications:
  slack:
    rooms:
      secure: LEJqH7gOp8LLQM3h4VZM/+NrNhIOJFYRZS2KmE43LPiqjEz1rkCIepWVyL5M8jvxJFGgiWY4ul9bI0hl7ni0l1ZXQe1MaQDtDwkz+e2jlpueydc6j84PaBTxOiYHd0s+7Ey8choNPITQByMpYlWHJJxWP6Z9cK3OzWDQZdIAdaZBZZWm26KaHC4cCKRNJPJTjTk6sLrEUFQcTXTDS0sNbHDigUmAlNoy4x6PGZM31oSzNB2izeImKlfxNWYKExEcQJuNFAFfEqujQ9zCxxKxyT1OqSYv5rl6lpoqhfN1MIOUuxWFd0zh8E1pcAxo7bX6O8ZkKfoRlWJYX6He9lxeTmgSAo6X7qCw95dye4t/irwGkVu87MhalxiZofmu4WAkF6w2O4GZu4ZmGX1nJZEXeWbTH+/8vLG7pq54FXk6FQqw6dPcxGbWE2le3G1vxVOAm5e510luHxztLEJioDDsZwPxQhjprhrfMSTfhw2laPJZD3bN/dx4hZABw5Rn5P4noLpG5fHsrh3lKK1wwsa1LdtODV3AYRWKkAZv76muhCZ2wXbCzBDPzTTmFIxNRF/019OVipkypY/l37HF/YMH3+6FWPbN4ENXeulcAbFrggHRt5QRImdOPeqPaanSfb3Pye0sHPF9az5h+HK7bAM81MLhD7gg2R+d/JERpFqu3UI=
