osx_image: xcode8
language: objective-c
cache: cocoapods
rvm: 2.2.3
before_install:
- gem install cocoapods --pre
- gem install xcpretty
- pod install --project-directory=Example --repo-update
script:
- set -o pipefail
- xcodebuild -workspace Example/MRLCircleChart.xcworkspace -scheme MRLCircleChart-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' CODE_SIGNING_REQUIRED=NO test | xcpretty
- xcodebuild -workspace Example/MRLCircleChart.xcworkspace -scheme MRLCircleChart-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' CODE_SIGNING_REQUIRED=NO test | xcpretty
- xcodebuild -workspace Example/MRLCircleChart.xcworkspace -scheme MRLCircleChart-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0' CODE_SIGNING_REQUIRED=NO test | xcpretty
